### ISSUE TITLE
No-fly list changes requested

### ISSUE THREAD

**Issue by Clavus** [Lowlands-Tactical/Lowlands-Tactical#12]
I hereby submit reasons to remove me from the no fly list.
https://www.youtube.com/watch?v=SaqYvzyOBqE
https://www.youtube.com/watch?v=BrkVJXBsg2g
Also it was never proven in court that this was me:
https://www.youtube.com/watch?v=CUtyUTLeW1g

**Comment by Ligthert** [comment]
HAHAHAHA!
Lol!

Nee.
