### ISSUE TITLE
Organiseer Joint-OP 2018Q4

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/Lowlands-Tactical#18]
De staf heeft sinds de Joint-OP met de duitsers de smaak ervan te pakken en zoekt nog een partij om Joint-OPs mee te organiseren.

Enkele zaken om naar te kijken bij een dergelijke Joint-OP zijn:

- Gebruik van ACE3
- Gebruik van ACRE2
- [Optioneel] Speelstijl komt overeen

Zaken waar vaak de nodige discussie over ontstaat zijn:
- Modset
- Datum en tijd
- Wie wat doet (scenarios/leiden?)

**Comment by Ligthert** [comment]
Ik heb al een lijntje uitgezet bij ARK.

**Comment by PekeNL** [comment]
Top. Ik denk qua modset inderdaad zo weinig mogelijk. Een barebones modset zorgt voor stabiliteit (preaching to the choir here...). Datum en tijd zijn altijd een hakkelpunt maar ik stel voor een zaterdag. Modset? persoonlijk @ACE, @ACRE2, @CBA met eventueel een eiland.
