### ISSUE TITLE
"We dun giffa fuck" afbeelding op de site plaatsen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/Lowlands-Tactical#2]
http://i.imgur.com/65ko3y1.jpg

**Comment by Ligthert** [comment]
@Mvelde0 Mist nog steeds. :-(

**Comment by Mvelde0** [comment]
Hoe wil je dit implementeren in een 'non-trigger' fashion? ;)

**Comment by PekeNL** [comment]
Ohgod. Laten we ons gewoon niet bezig houden met al die PC meuk.

**Comment by Ligthert** [comment]
Het idee was leuk. Dicht.
