### ISSUE TITLE
Lokale DB & www exporten en migreren naar de lowtac.nl host.

### ISSUE THREAD

**Issue by Mvelde0** [Lowlands-Tactical/Lowlands-Tactical#3]

**Comment by Ligthert** [comment]
URL!? :D

**Comment by Ligthert** [comment]
URL :-(

**Comment by Mvelde0** [comment]
- Voor de www kan ik [Duplicator](https://wordpress.org/plugins/duplicator/) gebruiken om de installatie iets makkelijker te maken.
- Zelfde geldt voor de DB. Dit is simpelweg een export via phpadmin.

De vraag is in hoe verre heb ik de rechten om dit uiteindelijk ook op de host te installen en niet met de huidige instellingen te lopen kloten.

**Comment by Mvelde0** [comment]
close
