### ISSUE TITLE
Media converten naar kleinere file size.

### ISSUE THREAD

**Issue by Mvelde0** [Lowlands-Tactical/Lowlands-Tactical#9]
Moeten evt. ook ff uitzoeken welke media we vernieuwd willen.

**Comment by Mvelde0** [comment]
@Flendurs Betreft de media, had jij nog nieuwe media die je wou gebruiken op de site? Anders kan ik net zo goed daar op wachten.

**Comment by Ligthert** [comment]
Voor nu is het wel goed zo.
